### ISSUE TITLE
Output is nonsense

### ISSUE THREAD

**Issue by dany-on-demand** [NiaSchim/auto-vicuna-butler#1]
Seems to be caused by web module being loaded before any other prompting

Latest commit, I've tried:

1. eachadea/ggml-vicuna-7b-1.1 + 13B
2. TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g-GGML
3. Original LLaMa converted to ggml, 7B,13B, 33B and 65B
4. Original LLaMa converted and quantized to 4bit

Prompt:
```
OpenAssistantAI
Find cat jokes on the internet
Search for cat jokes on the internet
Determine which ones are the best
Make variations
```

Occasionally the output somewhat resembles the objective/tasks, but doesn't actually do anything.

Also, it's really hard to exit the script, hitting ctrl+c once doesn't do anything. I need to press it many times in quick succession for it to stop.

Example output

eachadea/ggml-vicuna:

```to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: Please select one of the options: \_
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: OpenAssistantAI: Please enter a numbered response: \_
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: OpenAssistantAI: Please enter a numbered response: \_
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: OpenAssistantAI: Please enter a numbered response: \_
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: OpenAssistantAI: Please enter a numbered response: \_
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: OpenAssistantAI: Please enter a numbered response: \_
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session
```
(and so on)

TheBloke/ggml-vicuna:

```to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: Open Assistant AI
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: This is an AI that helps you get off your phone and back to work. Every time you try to do something on your phone, it asks you to do something else. It works by interfering with Google Assistant.
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session
```

LLaMa output was similar

New prompt:
OpenAssistantAI
```
Write a weather report for Paris tomorrow
Find a trusted weather prediction for the next week in Paris
Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you
Write the weather report using the data you gathered
```

Result (using TheBloke/ggml-vicuna):

```to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: I have chosen option 2.
Selected choice: 2
to OpenAssistantAI: Enter the hyperlink:
from OpenAssistantAI: ')
Exiting the loop to update the knowledge graph...
to OpenAssistantAI: Given my purpose ('Write a weather report for Paris tomorrow'), my 3 goals (Find a trusted weather prediction for the next week in Paris, Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you, Write the weather report using the data you gathered), my short-term memory, and my long-term memory, what goal should I work on next and how?
from OpenAssistantAI: Goal 2: Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you.
Goal 2: Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you.
to OpenAssistantAI: Summarize the following knowledge graphs, goals, and purpose:

Goals: Find a trusted weather prediction for the next week in Paris, Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you, Write the weather report using the data you gathered

Purpose: Write a weather report for Paris tomorrow

from OpenAssistantAI: Knowledge Graphs:
Knowledge Graphs:
to OpenAssistantAI: What are you doing?

from OpenAssistantAI: Me: I'm working on my goal of thinking about what a full weather report would look like and writing a critique of my thinking from the perspective of my best friend meteorologist who cares about me.
Model 13b:
Input: What are you doing?

Response: Me: I'm working on my goal of thinking about what a full weather report would look like and writing a critique of my thinking from the perspective of my best friend meteorologist who cares about me.

to OpenAssistantAI: What have you learned about what you're doing?

from OpenAssistantAI: Me: I've learned that writing a weather report involves including information about current weather conditions, a forecast for the future, and any relevant weather-related news or events. I've also learned that when writing a critique of my thinking, it's important to consider any biases or assumptions that may be impacting my analysis and to be open to alternative perspectives.
Model 13b:
Input: What have you learned about what you're doing?

Response: Me: I've learned that writing a weather report involves including information about current weather conditions, a forecast for the future, and any relevant weather-related news or events. I've also learned that when writing a critique of my thinking, it's important to consider any biases or assumptions that may be impacting my analysis and to be open to alternative perspectives.

to OpenAssistantAI: What have you learned in general?

from OpenAssistantAI: Me: I've learned that asking for help and receiving feedback is an important part of the learning process, and that by embracing my ignorance I can open myself up to new ideas and perspectives. I've also learned that being specific and clear in my requests is important to getting accurate and helpful responses.
Model 13b:
Input: What have you learned in general?

Response: Me: I've learned that asking for help and receiving feedback is an important part of the learning process, and that by embracing my ignorance I can open myself up to new ideas and perspectives. I've also learned that being specific and clear in my requests is important to getting accurate and helpful responses.

to OpenAssistantAI: Summarize the following text in less than 80 words:
Me: I'm working on my goal of thinking about what a full weather report would look like and writing a critique of my thinking from the perspective of my best friend meteorologist who cares about me.Me: I've learned that writing a weather report involves including information about current weather conditions, a forecast for the future, and any relevant weather-related news or events. I've also learned that when writing a critique of my thinking, it's important to consider any biases or assumptions that may be impacting my analysis and to be open to alternative perspectives.Me: I've learned that asking for help and receiving feedback is an important part of the learning process, and that by embracing my ignorance I can open myself up to new ideas and perspectives. I've also learned that being specific and clear in my requests is important to getting accurate and helpful responses.
from OpenAssistantAI: Request:
to OpenAssistantAI: Summarize the following text in less than 80 words:
Me: I'm working on my goal of thinking about what a full weather report would look like and writing a critique of my thinking from the perspective of my best friend meteorologist who cares about me.Me: I've learned that writing a weather report involves including information about current weather conditions, a forecast for the future, and any relevant weather-related news or events. I've also learned that when writing a critique of my thinking, it's important to consider any biases or assumptions that may be impacting my analysis and to be open to alternative perspectives.Me: I've learned that asking for help and receiving feedback is an important part of the learning process, and that by embracing my ignorance I can open myself up to new ideas and perspectives. I've also learned that being specific and clear in my requests is important to getting accurate and helpful responses.
from OpenAssistantAI:  #MySciFundCamp – A Unique Opportunity for Early Career Scientists
Traceback (most recent call last):
  File "C:\Projects\generative\llm\auto-vicuna-butler\autovicuna.py", line 136, in <module>
    web_browsing_module = browse_web(response_generator_big, response_generator_fast, knowledge_graph_updater_instance)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\generative\llm\auto-vicuna-butler\web_browsing_module.py", line 93, in browse_web
    knowledge_graph_updater_instance.summarize_and_store(visible_text) if choice == 1 else knowledge_graph_updater_instance.start()  # Update the knowledge graph
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\generative\llm\auto-vicuna-butler\knowledge_graph_updater.py", line 156, in start
    self.summarize_and_store(text)
  File "C:\Projects\generative\llm\auto-vicuna-butler\knowledge_graph_updater.py", line 190, in summarize_and_store
    with open(shortterm_filename, "w") as shortterm_file:
              ^^^^^^^^^^^^^^^^^^
NameError: name 'shortterm_filename' is not defined. Did you mean: 'shortterm_file'?
```

Second attempt:

```
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: Which action would you like to perform?
Sorry, I didn't understand your choice. Please enter a number between 0 and 6.
to OpenAssistantAI: Choose an action for web browsing, please pick only a single digit lonely numbered response; 0. Read unsummarized 1. Summarize page 2. Follow hyperlink 3. Enter URL 4. Last page (if applicable) 5. Next page (if applicable) 6. Exit browsing session

from OpenAssistantAI: Answer: 2 #
Selected choice: 2
to OpenAssistantAI: Enter the hyperlink:
from OpenAssistantAI: + OpenAssistantAI: Enter the hyperlink:
Exiting the loop to update the knowledge graph...
to OpenAssistantAI: Given my purpose ('Write a weather report for Paris tomorrow'), my 3 goals (Find a trusted weather prediction for the next week in Paris, Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you, Write the weather report using the data you gathered), my short-term memory, and my long-term memory, what goal should I work on next and how?
from OpenAssistantAI: Retrieval
Retrieval
to OpenAssistantAI: Summarize the following knowledge graphs, goals, and purpose:

Goals: Find a trusted weather prediction for the next week in Paris, Think about what a full weather report would look like, then write a critique of your thinking from the perspective of your best friend meteorologist who cares about you, Write the weather report using the data you gathered

Purpose: Write a weather report for Paris tomorrow

from OpenAssistantAI: Knowledge graph:
Knowledge graph:
to OpenAssistantAI: What are you doing?

from OpenAssistantAI: Me: I am working on a project where I am a memory AI and I am trying to find a way to help you with your goal.
Model 13b:
Input: What are you doing?

Response: Me: I am working on a project where I am a memory AI and I am trying to find a way to help you with your goal.

to OpenAssistantAI: What have you learned about what you're doing?

from OpenAssistantAI: Me: I have learned that I have a lot of information in my long-term memory but it's not always easy to access it. I also learned that my short-term memory is limited and it can't hold too much information.
Model 13b:
Input: What have you learned about what you're doing?

Response: Me: I have learned that I have a lot of information in my long-term memory but it's not always easy to access it. I also learned that my short-term memory is limited and it can't hold too much information.

to OpenAssistantAI: What have you learned in general?

from OpenAssistantAI: Me: I have learned that memory is a complex process that involves many different systems and mechanisms, and that different types of memories are stored in different ways. I have also learned about the different types of memory systems and the role of emotions in memory.
Model 13b:
Input: What have you learned in general?

Response: Me: I have learned that memory is a complex process that involves many different systems and mechanisms, and that different types of memories are stored in different ways. I have also learned about the different types of memory systems and the role of emotions in memory.

to OpenAssistantAI: Summarize the following text in less than 80 words:
Me: I am working on a project where I am a memory AI and I am trying to find a way to help you with your goal.Me: I have learned that I have a lot of information in my long-term memory but it's not always easy to access it. I also learned that my short-term memory is limited and it can't hold too much information.Me: I have learned that memory is a complex process that involves many different systems and mechanisms, and that different types of memories are stored in different ways. I have also learned about the different types of memory systems and the role of emotions in memory.
from OpenAssistantAI: Memory is a complex process that involves many different systems and mechanisms, and that different types of memories are stored in different ways. Home » News » Mental Health America Announces New President and CEO
to OpenAssistantAI: Summarize the following text in less than 80 words:
Me: I am working on a project where I am a memory AI and I am trying to find a way to help you with your goal.Me: I have learned that I have a lot of information in my long-term memory but it's not always easy to access it. I also learned that my short-term memory is limited and it can't hold too much information.Me: I have learned that memory is a complex process that involves many different systems and mechanisms, and that different types of memories are stored in different ways. I have also learned about the different types of memory systems and the role of emotions in memory.
from OpenAssistantAI:  391. The Birth of Venus - John Willi
```

**Comment by CRCODE22** [comment]
[results.txt](https://github.com/NiaSchim/auto-vicuna-butler/files/11256906/results.txt)

**Comment by dany-on-demand** [comment]
Author doesn't care, closing

**Comment by NiaSchim** [comment]
Thanks for the feedback.

I'm a bit slow on my response times.

I've kindof retired autovicuna butler in favor of hacking autogpt to have a
--vicuna argument instead.

**Comment by dany-on-demand** [comment]
https://github.com/Josh-XT/Agent-LLM/
https://github.com/BillSchumacher/Auto-Vicuna
